# Generated by Django 4.1.5 on 2024-11-27 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_userpassword_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpassword',
            name='paid',
            field=models.BooleanField(default=False),
        ),
    ]
